### ISSUE TITLE
request documentation or fix hostedDomain / hd parameter?

### ISSUE THREAD

**Issue by c0b** [jaredhanson/passport-google-oauth2#13]
I'm developing an application using Google authentication to allow a hosted domain users only,
google documentation says it support hd parameter to allow this restriction, this library seems have this support, but with this `new GoogleStrategy({  ... })` with `hostedDomain` or `hd` it doesn't make a difference, I don't see `&hd=...` parameter on the redirection url, when I manually append with `&hd=custom.com` that works;
So wonder is this passing `hostedDomain` to constructor the correct way to use it? request an example in REDME.md to clarify it; or fix if it's broken

https://github.com/jaredhanson/passport-google-oauth2/blob/master/lib/strategy.js#L159-L164
https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
https://developers.google.com/identity/sign-in/web/reference

```javascript
passport.use(new GoogleStrategy({
  clientID: config.get('OAUTH2_CLIENT_ID'),
  clientSecret: config.get('OAUTH2_CLIENT_SECRET'),
  callbackURL: config.get('OAUTH2_CALLBACK'),
  hostedDomain: config.get('OAUTH2_DOMAIN') || 'custom.com',
  // or hd: config.get('OAUTH2_DOMAIN') || 'custom.com',
  accessType: 'offline'
}, function (accessToken, refreshToken, profile, cb) {
   ...
   // here have to double validate profile.emails instead has such domain,
   // I found profile._json object has a domain attribute, like
       profile: { id: ..., displayName: ..., emails: [ ... ], photos: { ... }, _json: { domain: 'custom.com' } }
   // wonder why not expose the domain key to profile object?
```

**Comment by c0b** [comment]
I think I figured out it's on `passport.authenticate` call:

```javascript
passport.authenticate('google', {
  scope: [ 'email', 'profile', ... ],
  hostedDomain: config.get('OAUTH2_DOMAIN') || 'custom.com'
});
```

**Comment by cmnord** [comment]
Thanks @c0b!
