### ISSUE TITLE
Request: provide typings

### ISSUE THREAD

**Issue by ChrLipp** [jaredhanson/passport-google-oauth2#23]
I would like to request typings for this module installable with

    yarn add @types/passport-google-oauth20

There are typings under https://github.com/types/npm-passport-google-oauth20, but they are not available in the npm registry and are outdated.

**Comment by aitivinayak369** [comment]
Hi,
How to add this typing using npm.
Thanks

**Comment by NotAmaan** [comment]
@aitivinayak369 `npm i https://github.com/jaredhanson/passport-google-oauth2.git`

**Comment by aitivinayak369** [comment]
Thanks, bro!

**Comment by ezintz** [comment]
hey folks, just read: https://github.com/jaredhanson/passport-google-oauth2/issues/48

**Comment by jaredhanson** [comment]
Typings are available via an external package:

```sh
$ npm install @types/passport-google-oauth20
```
