### ISSUE TITLE
Whitelist specific domains

### ISSUE THREAD

**Issue by BenjaminRCooper** [jaredhanson/passport-google-oauth2#3]
Is it possible to whitelist specific domains?

For example, only people with '@someaddress.com' can log in

**Comment by levibostian** [comment]
I already do this @BenjaminRCooper. Well, manually. When user authenticates, I check the email address of the logged in user. If it is not of my domain, I call `callback('Error`, null);` and they cannot login.

**Comment by jaredhanson** [comment]
Thanks for the answer, @levibostian.

**Comment by BenjaminRCooper** [comment]
@levibostian - Do you have an example of this?

**Comment by levibostian** [comment]
```
var GoogleStrategy = require('passport-google-oauth20').Strategy;

passport.use(new GoogleStrategy({
    clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_CLIENT_SECRET,
    callbackURL: "http://www.example.com/auth/google/callback"
  },
  function(accessToken, refreshToken, profile, cb) {
    // Here. Check --> profile.emails[0].value.split('@')[1] === "
yourwebsitedomain.com"
  }
));
```
See the comment above that I made.

I believe you can also do the same thing here:
```
app.get('/auth/google',
  passport.authenticate('google', { scope: ['profile'] }));

app.get('/auth/google/callback',
  passport.authenticate('google', { failureRedirect: '/login' }),
  function(req, res) {
    // Here. Check --> req.user.emails[0].value.split('@')[1] === "
yourwebsitedomain.com"
    res.redirect('/');
  });
```

To be honest, I am not sure where it is "best" to check the email address.
I do it in the second example because I just return JSON back:
`res.send(new Error("You need to have a yourdomain.com email address to
join."));`. But I am not sure if this is the best way to do it.

**Comment by BenjaminRCooper** [comment]
Thanks @levibostian

**Comment by joeldenning** [comment]
For anyone else looking at this issue, you can accomplish this now with the following code:

```js
app.get('/auth/google/callback', passport.authenticate('google', {
  hostedDomain: 'example.com'
})
```

See [this line of code](https://github.com/jaredhanson/passport-google-oauth2/blob/aad7646d4d4413f50e2487a3e4b6df9672dbbd4f/lib/strategy.js#L159) where it is implemented.
