### ISSUE TITLE
Refresh token undefined 

### ISSUE THREAD

**Issue by natanbr** [jaredhanson/passport-google-oauth2#38]
Hi, 

I'm using passport to oAuth with google. In my callback after the user has logged in, although the parameters are: (request, accessToken, refreshToken, profile, done), the refreshToken is undefined while every other parameter is what it should be.
Whats wrong with the code?

This is the strategy config:
```
    clientID: process.env.GoogleClientID,
    clientSecret: process.env.GoogleClientSecret,
    callbackURL: process.env.GoogleCallbackURL,
    accessType: 'offline',
    prompt: 'consent',
    scope: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/userinfo.profile',
      'profile',
      'https://www.googleapis.com/auth/plus.login',
      'https://www.googleapis.com/auth/userinfo.email'],
    passReqToCallback: true
```
I already tried to delete all the cookies, and the app from the permissions... 
https://myaccount.google.com/u/0/permissions?pli=1

Thanks for your help

**Comment by natanbr** [comment]
Solution can be found [here](https://github.com/mstade/passport-google-oauth2/issues/5)

**Comment by Campermortey** [comment]
This did not fix it for me. Still unable to get the refresh token
