### ISSUE TITLE
use without express

### ISSUE THREAD

**Issue by bucibucii** [jaredhanson/passport-google-oauth2#63]
how to use it without express?
for example on a button click?

**Comment by toritsejuFO** [comment]
From the README:

This module lets you authenticate using Google **in your Node.js applications**. By plugging into Passport, Google authentication **can be easily and unobtrusively integrated into any application or framework that supports Connect-style middleware**, **including Express**.

It basically supports any connect-style middleware, not just express.

As for the button click though, I don't really get that. All you have to do is add a button on your client side app (be it hosted on the same server or and SPA), **and make a request to the URL that kicks that the auth flow, once the button is click.**

**Comment by bucibucii** [comment]
thanks!
