### ISSUE TITLE
Passport google oauth20 failed to authenticate with PKCE enabled

### ISSUE THREAD

**Issue by Wyfy0107** [jaredhanson/passport-google-oauth2#98]
When I use passport-google-oauth20 strategy with PKCE and state enabled, the user in callback of `passport.authenticate` is always `false`. After a bit of debugging, it seems once these 2 options are enabled, the verify callback of the strategy is not invoked. And I suppose because the verify callback was never invoked, `req.user` is always `false`. If setting those 2 options back to `false`, then the strategy works as expected

### Expected behavior
The verify callback is invoked with `accessToken`, `refreshToken`, and `req.user` has correct value.

### Actual behavior
Strategy verify callback is never invoked. `req.user` is always `false`

### Steps to reproduce
Here's the code in express

```js
const express = require('express')
const passport = require('passport')
const session = require('express-session')
const GoogleStrategy = require('passport-google-oauth20').Strategy

passport.use(
  new GoogleStrategy(
    {
      clientID: GOOGLE_CLIENT_ID,
      clientSecret: GOOGLE_CLIENT_SECRET,
      callbackURL: 'http://localhost:3000/auth/google/callback',
      passReqToCallback: true,
      pkce: true,
      state: true,
    },
    function (request, accessToken, refreshToken, profile, done) {
      console.log({ accessToken, refreshToken, profile, done })
      done(null, { test: 'hello' })
    }
  )
)

const app = express()

app.use(
  session({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: true,
    cookie: { secure: true },
  })
)
app.use(passport.initialize())

app.get(
  '/auth/google',
  passport.authenticate('google', {
    scope: ['email', 'profile'],
    session: true,
  })
)

app.get('/auth/google/callback', (req, res, next) => {
  passport.authenticate(
    'google',
    {
      session: true,
    },
    (error, user) => {
      if (error) {
        console.log({ error })
      }
      console.log({ user })

      res.send('Logged in')
    }
  )(req, res, next)
})

app.listen(3000)

```

### Environment

* Operating System: MacOS Ventura 13.3
* Node version: v20.3.0
* express: "^4.18.2"
* express-session: "^1.18.0"
* nodemon: "^3.0.3"
* passport: "^0.7.0" 
* passport-google-oauth20: "^2.0.0"

**Comment by Wyfy0107** [comment]
Manged to fix this when adding `passport.serializeUser` and `passport.deserializeUser`

**Comment by McTom234** [comment]
Hey @Wyfy0107, I am facing the same issue. What do your functions look like?
